name: Test Python Input

on:
   workflow_dispatch:
     inputs:
       myInput:
         description: 'User Input:'
         required: true
         default: "Hello World"

jobs:
  run-python-test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v3
  
     - name: Setup Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.9'
  
     - name: Execute Test Script
       run: |
         echo "Store: ${{ github.event.inputs.myInput }}"
         INPUT_STORE=${{ github.event.inputs.myInput }} python3 test.py
